# Generated by Django 4.2.5 on 2023-09-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CharityRegistrationTBL",
            fields=[
                ("phone", models.CharField(max_length=10,primary_key=True, serialize=False),),
                ("charityName", models.CharField(max_length=40)),
                ("email", models.CharField(max_length=30)),
                (
                    "RegistrationNumber",
                    models.CharField(max_length=40,default="NON CHARITY"),
                ),
                ("address", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "phone",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("Name", models.CharField(max_length=40)),
                ("email", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="LoginTBL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RegID", models.CharField(max_length=40)),
                ("Username", models.CharField(max_length=10)),
                ("Utype", models.IntegerField()),
                ("Status", models.IntegerField()),
            ],
        ),
    ]
