# Generated by Django 4.2.5 on 2023-09-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logintbl",
            name="Pass",
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
