# Generated by Django 4.2.5 on 2023-09-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_logintbl_pass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charityregistrationtbl",
            name="RegistrationNumber",
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="charityregistrationtbl",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
