# Generated by Django 4.2.5 on 2023-09-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_charityregistrationtbl_registrationnumber_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestDetailsTBL",
            fields=[
                ("DetailsId", models.AutoField(primary_key=True, serialize=False)),
                ("CharityRegistrationNumber", models.CharField(max_length=10)),
                ("Amount", models.CharField(max_length=20)),
                ("RequiredDate", models.DateField()),
                ("Details", models.TextField()),
                ("Priority", models.IntegerField(default=1)),
                ("Status", models.IntegerField()),
            ],
        ),
    ]
