# Generated by Django 4.2.5 on 2023-09-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_requestdetailstbl"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestdetailstbl",
            name="image",
            field=models.TextField(default="case1.png"),
        ),
    ]
