# Generated by Django 4.2.5 on 2023-09-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_requestdetailstbl_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="requestdetailstbl", name="image",),
    ]
