# Generated by Django 4.2.5 on 2023-09-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_financemanagement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charityregistrationtbl",
            name="RegistrationNumber",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="charityregistrationtbl",
            name="phone",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
